[1]
CAS = ["64-18-6", "7440-37-1"]
method = "CCSD(T)-F12/RI"
hash = "f6dbd8a12fdb62eff309a86b8363b8c1d864865f987070bd8b23ae494c51341e"
keywords = ["formic acid", "argon"]
file = "potential-1.jld"
basis = "cc-pVDZ-F12 cc-pVDZ-F12-CABS cc-pVTZ/C"
authors = ["Teemu Järvinen"]
description = "trans-formic acid - argon potential. Max 20000 cm⁻¹"
