[1]
CAS = ["64-18-6", "7440-37-1"]
method = "CCSD(T)-F12/RI"
"number of points" = 640
hash = "e36177f811c8df21df4fd15ff7fb04c9c1f0a858166acd84c19f13cdc21c0d9a"
keywords = ["formic acid", "argon"]
file = "potential-2.jld"
basis = "cc-pVDZ-F12 cc-pVDZ-F12-CABS cc-pVTZ/C"
authors = ["Teemu Järvinen"]
description = "trans-formic acid - argon potential. Max 20000 cm⁻¹"
