[1]
CAS = ["64-18-6", "7440-37-1"]
method = "CCSD(T)-F12/RI"
hash = "1f64ff73606825ba10a0ee006219a05a9491da0c9f855a4f458278e076cc0b5c"
keywords = ["formic acid", "argon"]
file = "potential-1.jld"
basis = "cc-pVDZ-F12 cc-pVDZ-F12-CABS cc-pVTZ/C"
authors = ["Teemu Järvinen"]
description = "trans-formic acid - argon potential. Max 20000 cm⁻¹"
